# Test values file for generating all of the yaml and check that
# the rendering is correct

volumePermissions:
  enabled: true

slave:
  replicas: 2

metrics:
  enabled: true
  ## Kubeval doesn't recognise ServiceMonitor as a valid K8s object
  # serviceMonitor:
  #   enabled: true
