apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "myweb.labels" . | nindent 4 }}
  name: myweb-nginx-conf 
data:
  default.conf: |-
    server {
      listen       80;
      server_name  127.0.0.1;
      client_max_body_size 5M;
      gzip on;
      server_tokens off;
      gzip_buffers 32 4K;#压缩在内存中缓冲32块 每块4K
      gzip_comp_level 6 ;#压缩级别 推荐6
      gzip_min_length 4000;#开始压缩的最小长度4bit
      gzip_types text/plain application/json application/javascript application/x-javascript application/css application/xml application/xml+rss text/javascript application/x-httpd-php image/jpeg image/gif image/png image/x-ms-bmp;
      
      location /cmdb/index/deploy/task/get_task_log/ {
        proxy_pass http://myweb:8000;
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # websocket配置
        proxy_http_version 1.1;
        proxy_set_header Upgrade "websocket";
        #proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        # 服务器返回状态码为101
        #HTTP/1.1 101 Switching Protocols
        #Upgrade: websocket
        #Connection: upgrade
      }
      
      #location /cmdb {
      #proxy_pass http://myweb:8000;
      #}
       
      #location /admin {
      #proxy_pass http://myweb:8000;
      #}
      
      location /admin {
        include  /etc/nginx/uwsgi_params;
        uwsgi_pass myweb:8001;
        uwsgi_ignore_client_abort on;
        uwsgi_read_timeout 600;
        uwsgi_connect_timeout 600;
        uwsgi_send_timeout 600;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
      
      location /cmdb {
        include  /etc/nginx/uwsgi_params;
        uwsgi_pass myweb:8001;
        uwsgi_ignore_client_abort on;
        uwsgi_read_timeout 600;
        uwsgi_connect_timeout 600;
        uwsgi_send_timeout 600;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
      
      location /cmdb/static {
        root /usr/share/nginx/html/;
      }
    }
