version: '2.3'

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "redhat"
      TZ: "Asia/Shanghai"
      LANG: "C.UTF-8"
    volumes:
    - ./data/mysql:/var/lib/mysql
    - ./conf/mysql/:/docker-entrypoint-initdb.d
    networks:
    - myweb-net
    ports:
    - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  redis:
    image: redis:3
    networks:
    - myweb-net
    ports:
    - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  myweb:
    image: chenhuxy/myweb:v2.3.9
    environment:
      LANG: "en_US.utf8"
    volumes:
    - ./conf/myweb/settings.py:/myweb/myweb/settings.py
    - ./logs/:/myweb/logs
    depends_on:
      mysql:
        condition: "service_healthy"
      redis:
        condition: "service_healthy"
    restart: always
    networks:
    - myweb-net
    ports:
    - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/admin"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    extra_hosts:
      - "gitlab.utfinancing.com:192.168.13.213"
      - "hygw.utfinancing.com:10.5.5.102"

networks:
  myweb-net:
    driver: bridge
    #enable_ipv6: true
    ipam:
      driver: default
