version: '2.3'

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "redhat"
      TZ: "Asia/Shanghai"
    volumes:
    - ./data/mysql:/var/lib/mysql
    - ./conf/mysql/:/docker-entrypoint-initdb.d
    networks:
    - myweb-net
    ports:
    - "3306:3306"

  redis:
    image: redis:3
    networks:
    - myweb-net
    ports:
    - "6379:6379"

  myweb:
    image: chenhuxy/myweb
    volumes:
    - ./conf/myweb/settings.py:/myweb/myweb/settings.py
    depends_on:
    - mysql
    - redis
    restart: always
    networks:
    - myweb-net
    ports:
    - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/admin"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  myweb-net:
    driver: bridge
    #enable_ipv6: true
    ipam:
      driver: default
