version: '2.3'

services:

  mysql:
    image: registry.cn-shanghai.aliyuncs.com/chenhuxy/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "redhat"
      TZ: "Asia/Shanghai"
      LANG: "C.UTF-8"
    volumes:
    - ./data/mysql:/var/lib/mysql
    - ./conf/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./conf/mysql/my.cnf:/etc/my.cnf
    networks:
    - myweb-net
    ports:
    - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-predhat"]
      interval: 60s
      timeout: 5s
      retries: 10
      start_period: 60s

  redis:
    image: registry.cn-shanghai.aliyuncs.com/chenhuxy/redis
    networks:
    - myweb-net
    ports:
    - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping", "-h", "localhost"]
      interval: 60s
      timeout: 5s
      retries: 10
      start_period: 60s
    command: ["redis-server", "--requirepass", "ssR*Yaw{(Pd7"]

  nginx:
    image: registry.cn-shanghai.aliyuncs.com/chenhuxy/nginx
    networks:
    - myweb-net
    ports:
    - "80:80"
    volumes:
    - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - static_vol:/usr/share/nginx/html/cmdb/static
    depends_on:
      myweb:
        condition: "service_healthy"

  myweb:
    image: registry.cn-shanghai.aliyuncs.com/chenhuxy/myweb:3.0.4
    environment:
      LANG: "en_US.utf8"
      #http_proxy: "http://1.1.1.1:3128"
      #no_proxy: "localhost,127.0.0.1,::1"
    volumes:
    - ./conf/myweb/settings.py:/myweb/myweb/settings.py
    - ./conf/myweb/uwsgi.ini:/myweb/apps/uwsgi/uwsgi.ini
    - ./logs/:/myweb/logs
    - static_vol:/myweb/static
    - ./data/ansible/:/etc/ansible
    depends_on:
      mysql:
        condition: "service_healthy"
      redis:
        condition: "service_healthy"
    restart: always
    networks:
    - myweb-net
    #ports:
    #- "8000:8000"
    #- "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/admin"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 60s
    extra_hosts:
      - "gitlab.utfinancing.com:192.168.13.213"
    #  - "xxx.com:2.2.2.2"

networks:
  myweb-net:
    driver: bridge
    #enable_ipv6: true
    ipam:
      driver: default

volumes:
  static_vol:
