version: '2.2'

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "redhat"
      TZ: "Asia/Shanghai"
    volumes:
    - ./data/mysql:/var/lib/mysql
    networks:
    - default
    ports:
    - "3306:3306"

  redis:
    image: redis:3
    networks:
    - default
    ports:
    - "6379:6379"

  myweb:
    image: chenhuxy/myweb
    volumes:
    - ./conf/settings.py:/myweb/myweb/settings.py
    depends_on:
    - mysql
    - redis
    restart: always
    networks:
    - default
    ports:
    - "8000:8000"

