# Generated by Django 2.1.7 on 2019-04-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190418_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_modify',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
