# Generated by Django 2.2 on 2019-04-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190418_2305'),
    ]

    operations = [
    ]
