# Generated by Django 2.2 on 2019-04-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190419_0944'),
    ]

    operations = [
    ]
