# Generated by Django 2.2 on 2019-04-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190419_1126'),
    ]

    operations = [
    ]
