# Generated by Django 2.1.4 on 2018-12-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('headImg', models.FileField(upload_to='./upload', verbose_name='文件名')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
