# Generated by Django 2.2.17 on 2021-06-25 16:31

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('workflow_order', models.IntegerField(default=0, verbose_name='工作流编号')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '登录用户',
                'verbose_name_plural': '登录用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_num', models.CharField(blank=True, max_length=256, null=True, verbose_name='机柜号')),
                ('cabinet_order', models.CharField(blank=True, max_length=256, null=True, verbose_name='机架号')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='设备管理员')),
            ],
            options={
                'verbose_name': '资产总表',
                'verbose_name_plural': '资产总表',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='合同号')),
                ('name', models.CharField(max_length=256, verbose_name='合同名称')),
                ('cost', models.IntegerField(verbose_name='合同金额')),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('license_num', models.IntegerField(blank=True, verbose_name='license数量')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未上线', max_length=256, verbose_name='名字')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '设备状态',
                'verbose_name_plural': '设备状态',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_display_name', models.CharField(default=None, max_length=256, verbose_name='区域名称')),
                ('display_name', models.CharField(default=None, max_length=256, verbose_name='机房名称')),
                ('floor', models.IntegerField(default=1, verbose_name='楼层')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
            },
        ),
        migrations.CreateModel(
            name='monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
            ],
            options={
                'verbose_name': '监控权限',
                'verbose_name_plural': '监控权限',
            },
        ),
        migrations.CreateModel(
            name='scriptType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='shell', max_length=200, verbose_name='脚本类型')),
            ],
            options={
                'verbose_name': '脚本类型',
                'verbose_name_plural': '脚本类型',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='标签名')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='wf_business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=128, verbose_name='业务单元')),
                ('proj_id', models.CharField(default=183, max_length=128, verbose_name='项目id')),
                ('repo', models.CharField(max_length=128, verbose_name='项目地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='业务管理员')),
                ('approval', models.ManyToManyField(blank=True, related_name='approval', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '业务单元',
                'verbose_name_plural': '业务单元',
            },
        ),
        migrations.CreateModel(
            name='wf_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='上线', max_length=128, verbose_name='请求类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工单类型',
                'verbose_name_plural': '工单类型',
            },
        ),
        migrations.CreateModel(
            name='wf_info_process_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, verbose_name='请求编号')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('sponsor', models.CharField(max_length=128, verbose_name='发起人')),
                ('content', models.TextField(blank=True, null=True, verbose_name='请求内容')),
                ('status', models.CharField(default='处理中', max_length=128, verbose_name='工单状态')),
                ('flow_id', models.IntegerField(verbose_name='流程id')),
                ('assignee', models.CharField(max_length=128, verbose_name='当前处理人')),
                ('next_assignee', models.CharField(max_length=128, verbose_name='下个处理人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('finish_time', models.DateTimeField(auto_now=True, verbose_name='完成时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('suggest', models.CharField(blank=True, max_length=128, null=True, verbose_name='审批结果')),
                ('suggest_content', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wf_business')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wf_type', verbose_name='请求类型')),
            ],
            options={
                'verbose_name': '工单流程历史',
                'verbose_name_plural': '工单流程历史',
            },
        ),
        migrations.CreateModel(
            name='wf_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128, verbose_name='请求编号')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('sponsor', models.CharField(max_length=128, verbose_name='发起人')),
                ('content', models.TextField(blank=True, null=True, verbose_name='请求内容')),
                ('status', models.CharField(default='未提交', max_length=128, verbose_name='工单状态')),
                ('flow_id', models.IntegerField(default=-1, verbose_name='流程id')),
                ('assignee', models.CharField(max_length=128, verbose_name='当前处理人')),
                ('next_assignee', models.CharField(max_length=128, verbose_name='下个处理人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('finish_time', models.DateTimeField(auto_now=True, verbose_name='完成时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wf_business')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wf_type', verbose_name='请求类型')),
            ],
            options={
                'verbose_name': '工单流程',
                'verbose_name_plural': '工单流程',
            },
        ),
        migrations.CreateModel(
            name='wf_business_deploy_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=128, verbose_name='业务单元')),
                ('proj_id', models.CharField(default=183, max_length=128, verbose_name='项目id')),
                ('repo', models.CharField(max_length=128, verbose_name='项目地址')),
                ('branch', models.CharField(max_length=128, verbose_name='项目分支')),
                ('tag', models.CharField(max_length=128, verbose_name='项目tag')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('state', models.CharField(max_length=128, verbose_name='发布状态')),
                ('logs', models.TextField(blank=True, null=True, verbose_name='发布日志')),
                ('opertator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '发布历史',
                'verbose_name_plural': '发布历史',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=128, unique=True, verbose_name='主机名')),
                ('sn', models.CharField(max_length=256, verbose_name='SN号')),
                ('manufactory', models.CharField(blank=True, max_length=256, null=True, verbose_name='厂商')),
                ('model', models.CharField(blank=True, max_length=256, null=True, verbose_name='型号')),
                ('bios', models.CharField(blank=True, max_length=256, null=True, verbose_name='BIOS')),
                ('type', models.BooleanField(default=False, verbose_name='虚拟机')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Asset')),
            ],
            options={
                'verbose_name': '服务器信息',
                'verbose_name_plural': '服务器信息',
                'index_together': {('sn', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='网卡名称')),
                ('model', models.CharField(blank=True, max_length=256, verbose_name='网卡型号')),
                ('ipaddr', models.GenericIPAddressField(verbose_name='ip地址')),
                ('mac', models.CharField(max_length=256, verbose_name='MAC地址')),
                ('netmask', models.CharField(blank=True, max_length=256, verbose_name='子网掩码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('server_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Server')),
            ],
            options={
                'verbose_name': '网卡信息',
                'verbose_name_plural': '网卡信息',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='设备名称')),
                ('sn', models.CharField(max_length=256, verbose_name='SN号')),
                ('manufactory', models.CharField(blank=True, max_length=256, null=True, verbose_name='厂商')),
                ('model', models.CharField(blank=True, max_length=256, null=True, verbose_name='型号')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Asset')),
            ],
            options={
                'verbose_name': '网络设备信息',
                'verbose_name_plural': '网络设备信息',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(blank=True, max_length=256, verbose_name='插槽名称')),
                ('model', models.CharField(blank=True, max_length=256, verbose_name='内存型号')),
                ('capacity', models.FloatField(blank=True, verbose_name='内存容量')),
                ('ifac_type', models.CharField(blank=True, max_length=256, verbose_name='接口类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('server_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Server')),
            ],
            options={
                'verbose_name': '内存信息',
                'verbose_name_plural': '内存信息',
            },
        ),
        migrations.CreateModel(
            name='HandleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_type', models.CharField(max_length=256, verbose_name='操作类型')),
                ('summary', models.CharField(max_length=256)),
                ('detail', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(blank=True, max_length=256, verbose_name='插槽名称')),
                ('model', models.CharField(blank=True, max_length=256, verbose_name='磁盘型号')),
                ('capacity', models.FloatField(blank=True, verbose_name='磁盘容量')),
                ('ifac_type', models.CharField(blank=True, max_length=256, verbose_name='接口类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('server_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Server')),
            ],
            options={
                'verbose_name': '磁盘信息',
                'verbose_name_plural': '磁盘信息',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='CPU名称')),
                ('model', models.CharField(blank=True, max_length=256, verbose_name='CPU型号')),
                ('core_num', models.IntegerField(blank=True, default=1, verbose_name='CPU核数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('server_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Server')),
            ],
            options={
                'verbose_name': 'CPU信息',
                'verbose_name_plural': 'CPU信息',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.wf_business', verbose_name='所属业务线'),
        ),
        migrations.AddField(
            model_name='asset',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Contract', verbose_name='合同'),
        ),
        migrations.AddField(
            model_name='asset',
            name='device_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.DeviceStatus'),
        ),
        migrations.AddField(
            model_name='asset',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.DeviceType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.IDC', verbose_name='idc机房'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tag',
            field=models.ManyToManyField(blank=True, to='myapp.Tag', verbose_name='标签'),
        ),
    ]
