# Generated by Django 2.2.17 on 2021-03-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wf_info_history_withdraw',
            name='flow_id',
            field=models.IntegerField(default=-1, verbose_name='流程id'),
        ),
    ]
