# Generated by Django 2.2.17 on 2021-05-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wf_business_deploy_history',
            name='logs',
            field=models.TextField(blank=True, null=True, verbose_name='发布日志'),
        ),
    ]
